import java.util.Scanner;
public class Main {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        double nota1;
        double nota2;
        System.out.println("Informe Nota 1 ");
        nota1 = input.nextDouble();

        System.out.println("Informe Nota 2 ");
        nota2 = input.nextDouble();

        if (((nota1+nota2)/2) == 10) {
            System.out.println("Aprovado com Distinção");

        } else if (((nota1+nota2)/2) >= 7) {
            System.out.println("Aprovado");

        }else if (((nota1+nota2)/2) < 7) {
            System.out.println("Reprovado");

        } else {
            System.out.println("Número Invalido"); }
    }
}