public class main {

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        int ano;

        System.out.println("Informe o ano: ");
        ano = input.nextInt();

        if (ano % 4 == 0) {
            System.out.println("Ano bisexto");

        } else if (ano % 400 == 0) {
            System.out.println("Ano bisexto");

        } else {
            System.out.println("Ano Não Bisexto");
        }
    }
    }