
import java.util.Scanner;
public class Main {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        String turno;
        System.out.println("Que turno você estuda. Digite M - Matutino V - Vespertino ou N - Noturno : ");

        turno = input.next();

        if (turno.equalsIgnoreCase("V")) {
            System.out.println("Boa Tarde");
        } else if (turno.equalsIgnoreCase("M")) {
            System.out.println("Bom Dia");
        } else if (turno.equalsIgnoreCase("N")) {
            System.out.println("Boa Noite");
        } else
            System.out.println("Valor Inválido ");

    }
}
